In [2]:
import pandas as pd
import numpy as np

json_path = "/home/psyph3ri0n/Documents/projects-2025/sur/downloads/qw/metadata/song_data.json"

#!/usr/bin/env python3
import json
import pandas as pd
import argparse

def json_to_csv(json_path: str, csv_path: str):
    # Load JSON
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Use pandas to normalize and flatten
    df = pd.json_normalize(
        data,
        sep="_"
    )
    
    # Optionally, rename columns for clarity
    # e.g. songdata_info_bpm -> bpm
    df.rename(columns=lambda c: c.replace("songdata_info_", ""), inplace=True)
    
    # Save to CSV
    df.to_csv(csv_path, index=False)
    print(f"✅ Saved CSV to {csv_path}")

In [3]:
df = json_to_csv(json_path, "/home/psyph3ri0n/Documents/projects-2025/sur/downloads/qw/metadata/song_data.csv")
# Convert the CSV to a DataFrame
df = pd.read_csv("/home/psyph3ri0n/Documents/projects-2025/sur/downloads/qw/metadata/song_data.csv")

✅ Saved CSV to /home/psyph3ri0n/Documents/projects-2025/sur/downloads/qw/metadata/song_data.csv

In [4]:
df.head()

,id,spotify_song_name,spotify_artist_name,youtube_title,file_path,lyrics_file_path,key,bpm,duration,camelot,...,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,popularity,release_date,songdata_track_url
0,1,Just,Radiohead,Radiohead - Just,downloads/qw/Radiohead - Just.mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,G Minor,176.0,3,6A,...,0.291,8.0,0.012000,0.0763,-6.913,0.0862,0.359,72.0,1995-03-13,NaN
1,2,Sinatra - 2005 Remaster,Deftones,Sinatra (2005 Remaster),downloads/qw/Sinatra (2005 Remaster).mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,84.0,4,11B,...,0.240,10.0,0.313000,0.1400,-4.305,0.0659,0.149,12.0,2005,NaN
2,3,Someday,The Strokes,The Strokes - Someday (Official HD Video),downloads/qw/The Strokes - Someday (Official H...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,106.0,3,11B,...,0.542,5.0,0.000002,0.3380,-7.481,0.0301,0.671,76.0,2001-07-30,NaN
3,4,Reptilia,The Strokes,The Strokes - Reptilia (Official HD Video),downloads/qw/The Strokes - Reptilia (Official ...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,158.0,3,11B,...,0.486,7.0,0.789000,0.1010,-5.084,0.0330,0.741,78.0,2003-10-28,NaN
4,5,Neshar Bojha,Popeye Bangladesh,Popeye(Bangladesh) - Neshar Bojha Lyrics Video,downloads/qw/Popeye(Bangladesh) - Neshar Bojha...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,E♭ Major,135.0,4,5B,...,0.478,5.0,0.000000,0.0666,-6.308,0.0354,0.311,0.0,2013-09-19,NaN

In [5]:
df.drop(columns=["songdata_track_url"], inplace=True)

In [6]:
df.head()

,id,spotify_song_name,spotify_artist_name,youtube_title,file_path,lyrics_file_path,key,bpm,duration,camelot,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,popularity,release_date
0,1,Just,Radiohead,Radiohead - Just,downloads/qw/Radiohead - Just.mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,G Minor,176.0,3,6A,0.000401,0.291,8.0,0.012000,0.0763,-6.913,0.0862,0.359,72.0,1995-03-13
1,2,Sinatra - 2005 Remaster,Deftones,Sinatra (2005 Remaster),downloads/qw/Sinatra (2005 Remaster).mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,84.0,4,11B,0.000149,0.240,10.0,0.313000,0.1400,-4.305,0.0659,0.149,12.0,2005
2,3,Someday,The Strokes,The Strokes - Someday (Official HD Video),downloads/qw/The Strokes - Someday (Official H...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,106.0,3,11B,0.003300,0.542,5.0,0.000002,0.3380,-7.481,0.0301,0.671,76.0,2001-07-30
3,4,Reptilia,The Strokes,The Strokes - Reptilia (Official HD Video),downloads/qw/The Strokes - Reptilia (Official ...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,158.0,3,11B,0.000563,0.486,7.0,0.789000,0.1010,-5.084,0.0330,0.741,78.0,2003-10-28
4,5,Neshar Bojha,Popeye Bangladesh,Popeye(Bangladesh) - Neshar Bojha Lyrics Video,downloads/qw/Popeye(Bangladesh) - Neshar Bojha...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,E♭ Major,135.0,4,5B,0.440000,0.478,5.0,0.000000,0.0666,-6.308,0.0354,0.311,0.0,2013-09-19

In [ ]:
def read_lyrics(lyrics_path: str):
    # Read the lyrics file
    with open(lyrics_path, "r", encoding="utf-8") as f:
        lyrics = f.read()
    
    return lyrics
def process_lyrics(lyrics: str):
    # Split the lyrics into lines
    lines = lyrics.split("<br>")
    
    # Remove empty lines and strip whitespace
    lines = [line.strip() for line in lines if line.strip()]
    
    # Join the lines back together
    processed_lyrics = "\n".join(lines)
    
    return processed_lyrics

# use the processed lyrics in a separate respective columns

In [15]:
#!/usr/bin/env python3
import os
import json
import pandas as pd

# === INPUT/OUTPUT PATHS ===
INPUT_JSON_PATH = "/home/psyph3ri0n/Documents/projects-2025/sur/downloads/qw/metadata/song_data.json"
OUTPUT_CSV_PATH = "playlist_with_lyrics.csv"

# === FUNCTIONS ===

def read_lyrics(lyrics_path: str) -> str:
    """Read the raw lyrics text from file."""
    try:
        with open(lyrics_path, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        print(f"❌ Failed to read lyrics at {lyrics_path}: {e}")
        return ""

def process_lyrics(lyrics: str) -> str:
    """Split on <br>, strip whitespace, remove empties, re-join with newlines."""
    lines = lyrics.split("<br>")
    lines = [line.strip() for line in lines if line.strip()]
    return "<br>\n".join(lines)

def main():
    # 1. Load and flatten JSON
    with open(INPUT_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    df = pd.json_normalize(data, sep="_")

    # 2. Rename nested songdata_info keys for cleanliness
    df.rename(columns=lambda c: c.replace("songdata_info_", ""), inplace=True)

    # 3. Extract and process lyrics
    raw_lyrics = []
    processed_lyrics = []
    for _, row in df.iterrows():
        lyrics_path = row.get("lyrics_file_path", "")
        raw = read_lyrics(lyrics_path) if os.path.exists(lyrics_path) else ""
        proc = process_lyrics(raw)
        raw_lyrics.append(raw)
        processed_lyrics.append(proc)

    df["raw_lyrics"] = raw_lyrics
    df["processed_lyrics"] = processed_lyrics

    # 4. Save to CSV
    df.to_csv(OUTPUT_CSV_PATH, index=False)
    print(f"✅ Lyrics-enhanced dataset saved to '{OUTPUT_CSV_PATH}'")

if __name__ == "__main__":
    main()

✅ Lyrics-enhanced dataset saved to 'playlist_with_lyrics.csv'

In [16]:
df = pd.read_csv(OUTPUT_CSV_PATH)
df.head()

,id,spotify_song_name,spotify_artist_name,youtube_title,file_path,lyrics_file_path,key,bpm,duration,camelot,...,instrumentalness,liveness,loudness,speechiness,valence,popularity,release_date,songdata_track_url,raw_lyrics,processed_lyrics
0,1,Just,Radiohead,Radiohead - Just,downloads/qw/Radiohead - Just.mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,G Minor,176.0,3,6A,...,0.012000,0.0763,-6.913,0.0862,0.359,72.0,1995-03-13,NaN,Can't get the stink off<br>\nHe's been hanging...,Can't get the stink off<br>\nHe's been hanging...
1,2,Sinatra - 2005 Remaster,Deftones,Sinatra (2005 Remaster),downloads/qw/Sinatra (2005 Remaster).mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,84.0,4,11B,...,0.313000,0.1400,-4.305,0.0659,0.149,12.0,2005,NaN,NaN,NaN
2,3,Someday,The Strokes,The Strokes - Someday (Official HD Video),downloads/qw/The Strokes - Someday (Official H...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,106.0,3,11B,...,0.000002,0.3380,-7.481,0.0301,0.671,76.0,2001-07-30,NaN,"In many ways, they'll miss the good old days<b...","In many ways, they'll miss the good old days<b..."
3,4,Reptilia,The Strokes,The Strokes - Reptilia (Official HD Video),downloads/qw/The Strokes - Reptilia (Official ...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,158.0,3,11B,...,0.789000,0.1010,-5.084,0.0330,0.741,78.0,2003-10-28,NaN,He seemed impressed by the way you came in<br>...,He seemed impressed by the way you came in<br>...
4,5,Neshar Bojha,Popeye Bangladesh,Popeye(Bangladesh) - Neshar Bojha Lyrics Video,downloads/qw/Popeye(Bangladesh) - Neshar Bojha...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,E♭ Major,135.0,4,5B,...,0.000000,0.0666,-6.308,0.0354,0.311,0.0,2013-09-19,NaN,NaN,NaN

In [17]:
# remove <br> and \n tags from the lyrics
df["processed_lyrics"] = df["processed_lyrics"].str.replace("<br>", "")
df["processed_lyrics"] = df["processed_lyrics"].str.replace("\n", "")

In [18]:
df.head()

,id,spotify_song_name,spotify_artist_name,youtube_title,file_path,lyrics_file_path,key,bpm,duration,camelot,...,instrumentalness,liveness,loudness,speechiness,valence,popularity,release_date,songdata_track_url,raw_lyrics,processed_lyrics
0,1,Just,Radiohead,Radiohead - Just,downloads/qw/Radiohead - Just.mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,G Minor,176.0,3,6A,...,0.012000,0.0763,-6.913,0.0862,0.359,72.0,1995-03-13,NaN,Can't get the stink off<br>\nHe's been hanging...,Can't get the stink offHe's been hanging 'roun...
1,2,Sinatra - 2005 Remaster,Deftones,Sinatra (2005 Remaster),downloads/qw/Sinatra (2005 Remaster).mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,84.0,4,11B,...,0.313000,0.1400,-4.305,0.0659,0.149,12.0,2005,NaN,NaN,NaN
2,3,Someday,The Strokes,The Strokes - Someday (Official HD Video),downloads/qw/The Strokes - Someday (Official H...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,106.0,3,11B,...,0.000002,0.3380,-7.481,0.0301,0.671,76.0,2001-07-30,NaN,"In many ways, they'll miss the good old days<b...","In many ways, they'll miss the good old daysSo..."
3,4,Reptilia,The Strokes,The Strokes - Reptilia (Official HD Video),downloads/qw/The Strokes - Reptilia (Official ...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,158.0,3,11B,...,0.789000,0.1010,-5.084,0.0330,0.741,78.0,2003-10-28,NaN,He seemed impressed by the way you came in<br>...,"He seemed impressed by the way you came in""Tel..."
4,5,Neshar Bojha,Popeye Bangladesh,Popeye(Bangladesh) - Neshar Bojha Lyrics Video,downloads/qw/Popeye(Bangladesh) - Neshar Bojha...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,E♭ Major,135.0,4,5B,...,0.000000,0.0666,-6.308,0.0354,0.311,0.0,2013-09-19,NaN,NaN,NaN

In [20]:
df.dropna(subset=["processed_lyrics"], inplace=True)
df.dropna(subset=["raw_lyrics"], inplace=True)
df.dropna(subset=["lyrics_file_path"], inplace=True)

In [22]:
df.head()

,id,spotify_song_name,spotify_artist_name,youtube_title,file_path,lyrics_file_path,key,bpm,duration,camelot,...,instrumentalness,liveness,loudness,speechiness,valence,popularity,release_date,songdata_track_url,raw_lyrics,processed_lyrics
0,1,Just,Radiohead,Radiohead - Just,downloads/qw/Radiohead - Just.mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,G Minor,176.0,3,6A,...,0.012000,0.0763,-6.913,0.0862,0.359,72.0,1995-03-13,NaN,Can't get the stink off<br>\nHe's been hanging...,Can't get the stink offHe's been hanging 'roun...
2,3,Someday,The Strokes,The Strokes - Someday (Official HD Video),downloads/qw/The Strokes - Someday (Official H...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,106.0,3,11B,...,0.000002,0.3380,-7.481,0.0301,0.671,76.0,2001-07-30,NaN,"In many ways, they'll miss the good old days<b...","In many ways, they'll miss the good old daysSo..."
3,4,Reptilia,The Strokes,The Strokes - Reptilia (Official HD Video),downloads/qw/The Strokes - Reptilia (Official ...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,158.0,3,11B,...,0.789000,0.1010,-5.084,0.0330,0.741,78.0,2003-10-28,NaN,He seemed impressed by the way you came in<br>...,"He seemed impressed by the way you came in""Tel..."

In [26]:
df.drop(columns=["lyrics_file_path", "youtube_title", "raw_lyrics"], inplace=True)

In [24]:
df.head()

,id,spotify_song_name,spotify_artist_name,youtube_title,file_path,lyrics_file_path,key,bpm,duration,camelot,...,energy,instrumentalness,liveness,loudness,speechiness,valence,popularity,release_date,raw_lyrics,processed_lyrics
0,1,Just,Radiohead,Radiohead - Just,downloads/qw/Radiohead - Just.mp3,/home/psyph3ri0n/Documents/projects-2025/sur/d...,G Minor,176.0,3,6A,...,8.0,0.012000,0.0763,-6.913,0.0862,0.359,72.0,1995-03-13,Can't get the stink off<br>\nHe's been hanging...,Can't get the stink offHe's been hanging 'roun...
2,3,Someday,The Strokes,The Strokes - Someday (Official HD Video),downloads/qw/The Strokes - Someday (Official H...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,106.0,3,11B,...,5.0,0.000002,0.3380,-7.481,0.0301,0.671,76.0,2001-07-30,"In many ways, they'll miss the good old days<b...","In many ways, they'll miss the good old daysSo..."
3,4,Reptilia,The Strokes,The Strokes - Reptilia (Official HD Video),downloads/qw/The Strokes - Reptilia (Official ...,/home/psyph3ri0n/Documents/projects-2025/sur/d...,A Major,158.0,3,11B,...,7.0,0.789000,0.1010,-5.084,0.0330,0.741,78.0,2003-10-28,He seemed impressed by the way you came in<br>...,"He seemed impressed by the way you came in""Tel..."